version: '3'
volumes:
  db_data:
  shared_data:
services:
  sudoku_redis:
    image: redis:4.0
    command: redis-server
    volumes:
      - shared_data:/var/shared/redis
  postgres:
    image: postgres:12.5
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  sudoku_app:
    build: .
    container_name: sudoku_app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    # stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    # command: bash -c "bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
  # sudoku_test:
  #   image: sudoku_app
  #   container_name: sudoku_test
  #   volumes:
  #     - .:/var/app
  #     - shared_data:/var/shared
  #     - gem_cache:/usr/local/bundle/gems
  #   networks:
  #     - test
  #   ports:
  #     - 3001:3000
  #   stdin_open: true
  #   tty: true
  #   env_file: .env.test
  #   entrypoint: test-entrypoint.sh
  #   command: ["rails", "-v"]
  #   environment:
  #     RAILS_ENV: test
  #   depends_on:
  #     - sudoku_db
